"use client"

import { AuthContextProvider } from '@/context/AuthContext'
import { Toaster } from "@/app/components/ui/toaster"
import { Inter } from "next/font/google";
import "@/app/static/globals.css";

const inter = Inter({subsets: ["latin"]});

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "Hagz",
//   description: "Generated by create next app", // Optimize metadata later
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col`}>
        <AuthContextProvider>
          {children}
          <Toaster/>
        </AuthContextProvider>
      </body>
    </html>
  );
}
