import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/static/globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Hagz",
  description: "Generated by create next app", // Optimize metadata later
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex flex-col`}>
          {children}
      </body>
    </html>
  );
}
